from pydantic import BaseModel

# on creation, we only need the user_id to link the account to a user
class AccountCreate(BaseModel):
    user_id: str

# on output, we want to include the account_id and created_at timestamp
class AccountOut(BaseModel):
    account_id: str # should be generated by the database
    user_id: str # reference to the user who owns the account
    balance: float
    account_type: str  # "CHECKING" or "SAVINGS"
    created_at: str