from pydantic import BaseModel

class Account(BaseModel):
    account_id: str # should be generated by the database
    user_id: str # reference to the user who owns the account
    balance: float
    account_type: str  # "CHECKING" or "SAVINGS"
    created_at: str