from pydantic import BaseModel

# on creation, we only need the account_id, txn_type, and amount to create a transaction
class TransactionCreate(BaseModel):
    account_id: str  # reference to the account involved in the transaction
    txn_type: str  # "deposit" or "withdrawal"
    amount: float

class TransactionOut(BaseModel):
    transaction_id: str # should be generated by the database
    account_id: str  # reference to the account involved in the transaction
    txn_type: str  # "deposit" or "withdrawal"
    amount: float
    created_at: str