from pydantic import BaseModel
class Transaction(BaseModel):
    transaction_id: str # should be generated by the database
    account_id: str  # reference to the account involved in the transaction
    txn_type: str  # "deposit" or "withdrawal"
    amount: float
    created_at: str